export const ERGEBNIS_SET_RANGE = 'ERGEBNIS_SET_RANGE';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const SCHREIBER_SET_KLASSE = 'SCHREIBER_SET_KLASSE';
export const SCHREIBER_SET_DISZIPLIN = 'SCHREIBER_SET_DISZIPLIN';
