export const ERGEBNIS_SET_RANGE = 'ERGEBNIS_SET_RANGE';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const SCHREIBER_SET_KLASSE = 'SCHREIBER_SET_KLASSE';
export const SCHREIBER_SET_DISZIPLIN = 'SCHREIBER_SET_DISZIPLIN';
export const SCHREIBER_INC_COUNTER = 'SCHREIBER_INC_COUNTER';
export const SCHREIBER_DEC_COUNTER = 'SCHREIBER_DEC_COUNTER';
export const SCHREIBER_SET_SCHUELER = 'SCHREIBER_SET_SCHUELER';
export const SCHREIBER_UPDATE_ERGEBNIS = 'SCHREIBER_UPDATE_ERGEBNIS';
export const SCHREIBER_SET_CURRENT_SCHUELER = 'SCHREIBER_SET_CURRENT_SCHUELER';
export const SCHREIBER_RESET = 'SCHREIBER_RESET';

export const NAVIGATION_SET_PAGE_NAME = 'NAVIGATION_SET_PAGE_NAME';
